### ISSUE TITLE
Disable a couple of annoying clippy lints

### ISSUE THREAD

**Issue by RobertJacobsonCDC** [CDCgov/ixa#299]
I would like to disable the following Clippy lints:

```toml
missing_panics_doc = "allow"
uninlined_format_args = "allow"
```

The first one is just too aggressive and encourages us to just write doc comments that are really just litter.

The second one I actually disagree with as a matter of style.

Any objections?
