### ISSUE TITLE
What fields of Ixa subcrates should default to the value of the workspace?

### ISSUE THREAD

**Issue by RobertJacobsonCDC** [CDCgov/ixa#336]
What fields of Ixa subcrates should default to the value of the workspace? A nonexhaustive list of possibilities:

```toml
[package]
name = "ixa-subcrate"
description = "An example of an Ixa subcrate"

authors.workspace = true # Currently not defined for the Ixa workspace
version.workspace = true # Should we synchronize versions?
license.workspace = true
edition.workspace = true
reposity.workspace = true
homepage.workspace = true

[lints]
# Each subcrate must opt in to workspace lints
workspace = true
```

The `version` field deserves particular consideration. Should we synchronize the versions of the aubcrates to the workspace?
