### ISSUE TITLE
Inherit workspace dependencies

### ISSUE THREAD

**Issue by RobertJacobsonCDC** [CDCgov/ixa#337]
Now that the Ixa repo is organized as a Cargo workspace, we should take advantage of workspace dependencies. In the `Cargo.toml` of the project root, you have a section:

```toml
[workspace.dependencies]
rand = "^0.8.5"
csv = "^1.3.1"
serde = { version = "^1.0.217", features = ["derive"] }
serde_derive = "^1.0.217"
serde_json = "^1.0.135"
# etc.
```

Then the `Cargo.toml` of each package (including potentially the same `Cargo.toml` in the project root, which doubles as the `Cargo.toml` for the `Ixa` package) you have:

```toml
[dependencies]
rand.workspace = true
serde.workspace = true
# any other packages listed in the dependencies of the workspace
```

The point of doing this is:

- DRY: one source of truth for path, version, features.
- Consistency: no accidental version mismatches between members.
- Ease of updates: bump a version in exactly one place and cargo update rolls it out everywhere.
- Overrideable: individual members can still tweak features or add optional flags on a per-crate basis.

(This will implicitly establish a MSRV of 1.62, which introduced workspace dependencies.)
