### ISSUE TITLE
Opt in workspace members to workspace lint exceptions

### ISSUE THREAD

**Issue by RobertJacobsonCDC** [CDCgov/ixa#339]
Workspace lint settings are defined in the root `Cargo.toml`:

```toml
[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
module-name-repetitions = "allow"
implicit_hasher = "allow"
missing_panics_doc = "allow"
uninlined_format_args = "allow"
```

Members of the workspace have to opt into these settings by including the following in their own `Cargo.toml`:

```toml
[lints]
workspace = true
```

This issue is for including this section in each workspace member's `Cargo.toml`.
