### ISSUE TITLE
Investigate whether dependencies in births-deaths are from macro use

### ISSUE THREAD

**Issue by RobertJacobsonCDC** [CDCgov/ixa#352]
I am suspicious of the dependencies of, for example, `births-deaths` (possibly elsewhere):

```toml
csv.workspace = true
ctor.workspace = true
serde.workspace = true
rand.workspace = true
rand_distr.workspace = true
paste.workspace = true
```

These look like they might be from macro usage. If so, restructure the macro to use the dependency from the crate it originates from instead of requiring the dependent crate to know about and add the dependency.
